import '../global.css';
import { Inter } from 'next/font/google';
import DashboardWrapper from './dashboard/dashboardWrapper';

export const metadata = {
  title: 'Welcome to next-directory-client',
  description: 'Generated by create-nx-workspace',
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DashboardWrapper>{children}</DashboardWrapper>
      </body>
    </html>
  );
}
